### ISSUE TITLE
ClassFieldsAndMethodsCache not threadsafe

### ISSUE THREAD

**Issue by martin-nagy** [i-Cell-Mobilsoft-Open-Source/coffee#636]
**Describe the bug**
If you call ClassFieldsAndMethodsCache from multiple threads you get a ConcurrentModificationException

```java
hu.icellmobilsoft.coffee.dto.exception.TechnicalException: Error in saving [XXX]: [null]
	at deployment.ROOT.war//hu.icellmobilsoft.coffee.jpa.service.BaseService.save(BaseService.java:209)
	...
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at deployment.ROOT.war//hu.icellmobilsoft.coffee.model.base.ClassFieldsAndMethodsCache.getFieldsAndMethods(ClassFieldsAndMethodsCache.java:94)
	at deployment.ROOT.war//hu.icellmobilsoft.coffee.model.base.AbstractProvider.getAllFieldsAndMethods(AbstractProvider.java:70)
	at deployment.ROOT.war//hu.icellmobilsoft.coffee.model.base.javatime.listener.TimestampsProvider.updateTimestamps(TimestampsProvider.java:83)
	at deployment.ROOT.war//hu.icellmobilsoft.coffee.model.base.javatime.listener.TimestampsProvider.prePersist(TimestampsProvider.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate@6.1.5.Final//org.hibernate.jpa.event.internal.ListenerCallback.performCallback(ListenerCallback.java:55)
	at org.hibernate@6.1.5.Final//org.hibernate.jpa.event.internal.CallbackRegistryImpl.callback(CallbackRegistryImpl.java:96)
	at org.hibernate@6.1.5.Final//org.hibernate.jpa.event.internal.CallbackRegistryImpl.preCreate(CallbackRegistryImpl.java:56)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultMergeEventListener.saveTransientEntity(DefaultMergeEventListener.java:308)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:247)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:179)
	at org.hibernate@6.1.5.Final//org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:76)
	at org.hibernate@6.1.5.Final//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:828)
	at org.hibernate@6.1.5.Final//org.hibernate.internal.SessionImpl.merge(SessionImpl.java:814)
	at org.jboss.as.jpa@27.0.1.Final//org.jboss.as.jpa.container.AbstractEntityManager.merge(AbstractEntityManager.java:568)
	at deployment.ROOT.war//hu.icellmobilsoft.coffee.jpa.service.BaseService.save(BaseService.java:197)
	... 66 more
```

**To Reproduce**
1. Create multiple threads, and try to save entities in every thread with same class

**Affected system:**
 - Subsystem, module: coffee-model-base
 - Version: 2.0.0+

**Comment by martin-nagy** [comment]
Already fixed in the newest version
