### ISSUE TITLE
ETCD kulcs hiánynál túl nagy a stacktrace

### ISSUE THREAD

**Issue by rombow** [i-Cell-Mobilsoft-Open-Source/coffee#68]
hu.icellmobilsoft.coffee.rest.configuration.ApplicationConfiguration túl sokat logol és `ERROR` szinten. Ha nincs kulcs, akkor elég `WARN` és nem kell az egész stacktrace
```
[2020-09-15 09:18:11.667 ERROR [thread:default task-1] [hu.icellmobilsoft.coffee.rest.configuration.ApplicationConfiguration] [sid:33PH0YAHTUQHJ301] - Error in getting configuration for key [etcd.sample.key]: [hu.icellmobilsoft.coffee.dto.exception.TechnicalException: Etcd value not found, key: [etcd.sample.key] valueClass: [class java.lang.Boolean]!]: java.util.concurrent.ExecutionException: hu.icellmobilsoft.coffee.dto.exception.TechnicalException: Etcd value not found, key: [etcd.sample.key] valueClass: [class java.lang.Boolean]!
 	at com.google.guava//com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
 	at com.google.guava//com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:487)
 	at com.google.guava//com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
 	at com.google.guava//com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:196)
 	at com.google.guava//com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2313)
...
```

**Comment by cserhatit** [comment]
szerintem ezzel az #56 is megoldodik
